(defun beautify-java ()
  (interactive)
  (untabify (point-min) (point-max))
  (goto-char 0)
  (while (re-search-forward "" nil t)
    (replace-match ""))
  (goto-char 0)
  (while (re-search-forward "//.*\n" nil t)
    (replace-match ""))
  (goto-char 0)
  (while (re-search-forward "/\\*.*?\\*/" nil t)
    (replace-match ""))
  (goto-char 0)
  (while (re-search-forward "\s*\n" nil t)
    (replace-match "\n"))
  (goto-char 0)
  (while (re-search-forward "\r" nil t)
    (replace-match "\n"))
  (goto-char 0)
  (while (re-search-forward "\n\n+" nil t)
    (replace-match "\n"))
  (goto-char 0)
  (while (re-search-forward "\n[ \n]*\\(public\\|private\\|protected\\|static\\|final\\)" nil t)
    (replace-match "\n\n\\1"))
  (goto-char 0)
  (while (re-search-forward "}[ \n]*else" nil t)
    (replace-match "} else"))
  (goto-char 0)
  (while (re-search-forward ";" nil t)
    (replace-match ";\n"))
  (goto-char 0)
  (while (re-search-forward "{" nil t)
    (replace-match "{\n"))
  (goto-char 0)
  (while (re-search-forward "  " nil t)
    (replace-match " "))
  (goto-char 0)
  (while (re-search-forward ";\n\n" nil t)
    (replace-match ";\n"))
  (goto-char 0)
  (while (re-search-forward "\n\s*;" nil t)
    (replace-match ";"))
  (goto-char 0)
  (while (re-search-forward "{\n\n" nil t)
    (replace-match "{\n"))
  (goto-char 0)
  (while (re-search-forward "\n\s*{" nil t)
    (replace-match "{"))
  (goto-char 0)
  (while (re-search-forward "[\n\s]*extends\s+\\(.*\\)\n" nil t)
    (replace-match " extends \\1 \n"))
  (goto-char 0)
  (while (re-search-forward "[\n\s]*implements\s+\\(.*\\)\n" nil t)
    (replace-match " implements \\1 \n"))
  (goto-char 0)
  (while (re-search-forward "\n\\(.*\\)\sclass\s\\(.*\\)\n" nil t)
    (replace-match "\n\n\\1 class \\2\n\n"))
  (goto-char 0)
  (while (re-search-forward "\s*package\s\\(.*\\)\n" nil t)
    (replace-match "package \\1\n\n"))
  (goto-char 0)
  (delete-trailing-whitespace)
  (indent-region (point-min) (point-max) nil)
  )
